this.AdminConfig = {
  name: Config.name,
  adminEmails: ['i.deiudicibus@gmail.com'],
  collections: {
    'Meteor.roles':{
        color:'green',
        icon:'users',
        tableColumns:[
            {
                label:'Name',
                name:'name'
            }
        ]
    },
    Players: {
      color: 'red',
      icon: 'soccer-ball-o',
      extraFields: ['owner'],
      tableColumns: [
        {
          label: 'Full name',
          name: 'fullName'
        }, {
          label: 'Nationality',
          name: 'nationality'
        }
      ]
    },
    PlayerStats:{
      color: 'green',
      icon:'group',
      tableColumns:[
        {label:'Player',name:'playerRef()',template:'playerNameCell'},
         {label:'Season',name:'season'},
         {label:'Club',name:'clubRef()',template:'clubNameCell'},
         {label:'goals',name:'goals'}

      ],
       extraFields: ['player','club']
    },
    Clubs:{
      color: 'yellow',
      icon:'group',
      tableColumns:[
          {label:'name',name:'name'},
          {label:'nationality',name:'nationality'}
      ]
    },
    Donations: {
      color: 'red',
      icon:'eur',
      tableColumns:[
          {label:'email',name:'givenEmail'},
          {label:'amount',name:'amount'},
          {label:'Transaction Date',name:'transactionDate'},
          {label:'Player',name:'playerRef()',template:'playerNameCell'}
      ],
      extraFields: ['player']
    },
    Transfers:{
      color: 'green',
      icon:'exchange',
      tableColumns:[
          {label:'Date',name:'date',template:'formattedDateCell'},
          
          {label:'Buyer Club',name:'buyerClubRef()',template:'buyerClubNameCell'},
          {label:'Seller Club',name:'sellerClubRef()',template:'sellerClubNameCell'},
          {label:'Value',name:'market_value'},
          {label:'Payback',name:'payback_value'},
          {label:'Player',name:'playerRef()',template:'playerNameCell'}
      ],
      extraFields: ['player','buyer_club','seller_club']
    },
    Posts: {
      color: 'red',
      icon: 'pencil',
      extraFields: ['owner'],
      tableColumns: [
        {
          label: 'Title',
          name: 'title'
        }, {
          label: 'User',
          name: 'author()',
          template: 'adminUserCell'
        }
      ]
    },
    Comments: {
      color: 'green',
      icon: 'comments',
      extraFields: ['doc', 'owner'],
      tableColumns: [
        {
          label: 'Content',
          name: 'content'
        }, {
          label: 'Post',
          name: 'docTitle()',
          template: 'adminPostCell'
        }, {
          label: 'User',
          name: 'author()',
          template: 'adminUserCell'
        }
      ],
      children: [
        {
          find: function(comment) {
            return Posts.find(comment.doc, {
              limit: 1
            });
          }
        }, {
          find: function(comment) {
            return Meteor.users.find(comment.owner, {
              limit: 1
            });
          }
        }
      ]
    }
  },
  dashboard: {
    homeUrl: '/'
  },
  autoForm: {
    omitFields: ['createdAt', 'updatedAt']
  }
};

// ---
// generated by coffee-script 1.9.2